export const AuditEvent = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_LOGIN_FAILED: 'auth.login_failed',
  AUTH_PASSWORD_CHANGE: 'auth.password_change',
  ADMIN_USER_CREATED: 'admin.user_created',
  ADMIN_USER_UPDATED: 'admin.user_updated',
  ADMIN_USER_DELETED: 'admin.user_deleted',
  ADMIN_META_UPDATED: 'admin.meta_updated',
  SEGMENT_CREATED: 'segment.created',
  SEGMENT_UPDATED: 'segment.updated',
  SEGMENT_DELETED: 'segment.deleted',
  CONTACT_CREATED: 'contact.created',
  CONTACT_IMPORT: 'contact.import',
  CONTACT_BULK_SEGMENT: 'contact.bulk_segment',
  CONTACT_UPDATED: 'contact.updated',
  CONTACT_DELETED: 'contact.deleted',
  CAMPAIGN_CREATED: 'campaign.created',
  CAMPAIGN_RETRY_MANUAL: 'campaign.retry_manual',
  TEMPLATE_SYNC: 'template.sync',
  CONVERSATION_MODE: 'conversation.mode',
  CONVERSATION_REPLY: 'conversation.reply',
  CONVERSATION_EXPORT: 'conversation.export',
  CONVERSATION_MEDIA_DOWNLOAD: 'conversation.media_download',
  SETTINGS_AI_CONFIG: 'settings.ai_config',
  SETTINGS_AI_ENABLE: 'settings.ai_enable',
  SETTINGS_BUSINESS_HOURS: 'settings.business_hours',
} as const;

export type AuditEventType = (typeof AuditEvent)[keyof typeof AuditEvent];
