FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY api/package.json ./api/
COPY web/package.json ./web/

RUN npm install

COPY api ./api

RUN npm run prisma:generate -w api

EXPOSE 4000

CMD ["npm", "run", "dev:api"]
