FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY api/package.json ./api/
COPY api/prisma ./api/prisma
COPY web/package.json ./web/

RUN npm install

COPY web ./web

EXPOSE 5173

CMD ["sh", "-c", "npm run dev -w web -- --host 0.0.0.0"]
